output_dir: "mcmc_results"
run_mcmc: false
reference_data: "results_test/results.json"
plotting: true
#======CONFIG=====================
# config_settings:
#   thruster:
#     name: "SPT-100"
#   anom_model: #
# #UNCOMMENT and CUSTOMIZE
#     TwoZoneBohm: 
#       c1: 0.00625
#       c2: 0.0625
settings:
  initial_cs: [0.2, 0.1]
  initial_cov: [[1.0, 0.0], [0.0, 1.0]]
  max_iter: 100
  burn_in: 50

    
