output_dir: "map_results"
run_map: false
reference_data: "${settings.output_dir}/postprocess/output_multilogbohm.json"
plotting: true
map_settings:
  initial_cs: [0.2, 0.1]
  max_iter: 100
  algorithm: 'slsqp'
    
