output_dir: "map_results"
run_map: true

reference_data: "results_test/results.json"

#======CONFIG=====================
config_settings:
  thruster:
    name: "SPT-100"
  anom_model: #  anom model needs to be specified.(parameters)
#UNCOMMENT TWOZONEBOHM FOR MCMC/MAP 
    TwoZoneBohm: 
      c1: 0.00625
      c2: 0.0625

settings:
  initial_cs: [0.2, 0.1]
  max_iter: 100
  algorithm: 'slsqp'
    

