#mcmc.yaml
save_interval: 10
checkpoint_interval: 10
save_metadata: true
final_samples_file_log: "mcmc_results/mcmc-results-1/final_samples_log.csv"
final_samples_file_linear: "mcmc_results/mcmc-results-1/final_samples_linear.csv"
checkpoint_file: "mcmc_results/mcmc-results-1/checkpoint.json"
metadata_file: "mcmc_results/mcmc-results-1/mcmc_metadata.json"
initial_cov:
  - [0.1, 0.05]
  - [0.05, 0.1]  