plotting:
  base_results_dir: "/home/elida/Public/users/elsensoy/model_error_uq_plasma/hall_opt/results"
  plots_subdir: "plots-mcmc"
  metrics_subdir: "iteration_metrics"

  files:
    samples: "mcmc/final_samples_linear.csv"
    truth_data: "mcmc_observed_data_map.json"
    pre_mcmc_data: "mcmc_pre_mcmc_initial.json"
    initial_params: "initial_map_log.json"

  general_plot_settings:
    enable_plots: true
    save_format: "png"
    plotting_backend: "matplotlib"  
    subsample_step: 10  

enabled_plots:
  - autocorrelation
  - trace
  - posterior
  - pairplot
