general:
  results_dir: "hall_opt/results"  # Base directory for results
  run_map: false    # Whether to run MAP
  run_mcmc: false   # Whether to run MCMC
  plotting: false   # Whether to generate plots
  ion_velocity_weight: 2.0 #same for both mcmc and map
  iterations: 20   # Number of iterations

config_settings:
    thruster:
      name: "SPT-100"
      geometry:
        channel_length: 0.025
        inner_radius: 0.0345
        outer_radius: 0.05
      magnetic_field:
        file: "hall_opt/config/bfield_spt100.csv"
    discharge_voltage: 300
    anode_mass_flow_rate: 5.0e-6
    domain: [0, 0.08]
    ncharge: 3
    anom_model:   # **THIS FIELD MUST EXIST**
      TwoZoneBohm:
        c1: 0.00625
        c2: 0.0625
      MultiLogBohm:
        zs: [0.0, 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07]
        cs: [0.02, 0.024, 0.028, 0.033, 0.04, 0.004, 0.004, 0.05]
    postprocess:   #  **THIS FIELD MUST EXIST**
      output_file:
        TwoZoneBohm: "hall_opt/results/output_twozonebohm.json"
        MultiLogBohm: "hall_opt/results/output_multilogbohm.json"
      save_time_resolved: false
      average_start_time:  0.4e-3

ground_truth:
  gen_data: true  # Whether to generate data

#mcmc.yaml
mcmc:
  save_interval: 10
  checkpoint_interval: 10
  save_metadata: true
  final_samples_file_log: "mcmc_results/mcmc-results-1/final_samples_log.csv"
  final_samples_file_linear: "mcmc_results/mcmc-results-1/final_samples_linear.csv"
  checkpoint_file: "mcmc_results/mcmc-results-1/checkpoint.json"
  metadata_file: "mcmc_results/mcmc-results-1/mcmc_metadata.json"
  initial_cov:
    - [0.1, 0.05]
    - [0.05, 0.1]  

  #map.yaml
map:
  map_initial_guess_file: "map_results/initial_guess.json"
  iteration_log_file: "map_results/map_iterations.json"
  final_map_params_file: "map_results/final_map_params.json"
  method: "Nelder-Mead"
  maxfev: 5000
  fatol: 0.003
  xatol: 0.003

plots:
  plots_subdir: "plots-mcmc"
  metrics_subdir: "iteration_metrics"
  enabled_plots:
    - "autocorrelation"
    - "trace"
    - "posterior"
    - "metric_plots"