results_dir: "/mnt/c/Users/elsensoy/model_error_uq_plasma/hall_opt/results"
gen_data: true
run_map: true
run_mcmc: false
ion_velocity_weight: 2.0
plotting: false
initial_guess_path: "/mnt/c/Users/elsensoy/model_error_uq_plasma/hall_opt/results/map_results/initial_guess.json"
optimized_param: "/mnt/c/Users/elsensoy/model_error_uq_plasma/hall_opt/results/map_results/final_parameters.json"
iterations: 1000
initial_cov:
  - [0.1, -0.5]
  - [-0.5, 0.1]

# Simulation configurations
config_multilogbohm:
  thruster:
    name: "SPT-100"
    geometry:
      channel_length: 0.025
      inner_radius: 0.0345
      outer_radius: 0.05
    magnetic_field:
      file: "hall_opt/config/bfield_spt100.csv"
  discharge_voltage: 300.0
  anode_mass_flow_rate: 1e-5
  domain: [0.0, 0.08]
  anom_model:
    type: "MultiLogBohm"
    zs: [0.0, 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07]
    cs: [0.02, 0.024, 0.028, 0.033, 0.04, 0.004, 0.004, 0.05]
  ncharge: 3

config_spt_100:
  thruster:
    name: "SPT-100"
    geometry:
      channel_length: 0.025
      inner_radius: 0.0345
      outer_radius: 0.05
    magnetic_field:
      file: "hall_opt/config/bfield_spt100.csv"
  discharge_voltage: 300.0
  anode_mass_flow_rate: 5e-6
  domain: [0.0, 0.08]
  anom_model:
    type: "TwoZoneBohm"
    c1: -2.0
    c2: 0.5
  ncharge: 3

simulation:
  dt: 1e-6
  adaptive: true
  grid:
    type: "EvenGrid"
    num_cells: 100
  num_save: 100
  duration: 0.001

postprocess:
  output_file: "./results/output_twozonebohm.json"
  save_time_resolved: false
  average_start_time: 0.0004

