general_settings:
  results_dir: "/home/elida/Public/users/elsensoy/model_error_uq_plasma/hall_opt/results"
  gen_data: true
  run_map: false
  run_mcmc: true
  ion_velocity_weight: 2.0
  plotting: false
  iterations: 20

optimization_params:
  # MAP parameters
  map_params:
    method: "Nelder-Mead"
    map_initial_guess_path: "/home/elida/Public/users/elsensoy/model_error_uq_plasma/hall_opt/results/map_results/initial_guess.json"
    maxfev: 5000          # Maximum number of function evaluations
    fatol: 0.003           # Function tolerance
    xatol: 0.003          # Step size tolerance
    iteration_log_file: "/home/elida/Public/users/elsensoy/model_error_uq_plasma/hall_opt/results/map_results/map_iterations.json"
    final_map_params: "/home/elida/Public/users/elsensoy/model_error_uq_plasma/hall_opt/results/map_results/final_map_params.json"

  # MCMC parameters
  mcmc_params:
    save_interval: 10
    checkpoint_interval: 10
    save_metadata: true
    final_samples_file_log: "/home/elida/Public/users/elsensoy/model_error_uq_plasma/hall_opt/results/mcmc/final_samples_log.csv"
    final_samples_file_linear: "/home/elida/Public/users/elsensoy/model_error_uq_plasma/hall_opt/results/mcmc/final_samples_linear.csv"
    checkpoint_file: "/home/elida/Public/users/elsensoy/model_error_uq_plasma/hall_opt/results/mcmc/checkpoint.json"
    metadata_file: "/home/elida/Public/users/elsensoy/model_error_uq_plasma/hall_opt/results/mcmc/mcmc_metadata.json"
    initial_cov:
      - [0.1, 0.05]
      - [0.05, 0.1]  
config:
  thruster:
    name: "SPT-100"
    geometry:
      channel_length: 0.025
      inner_radius: 0.0345
      outer_radius: 0.05
    magnetic_field:
      file: "hall_opt/config/bfield_spt100.csv"
  discharge_voltage: 300
  anode_mass_flow_rate: 0.0001
  domain: [0, 0.08]
  propellant: Xenon
  ion_wall_losses: true
  solve_plume: false
  apply_thrust_divergence_correction: true
  neutral_ingestion_multiplier: 1.0
  ncharge: 3
  transition_length: 0.003
  neutral_velocity: 300
  anom_model:
    TwoZoneBohm:
      c1: 0.00625
      c2: 0.0625
    MultiLogBohm:
      zs: [0.0, 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07]
      cs: [0.02, 0.024, 0.028, 0.033, 0.04, 0.004, 0.004, 0.05]

simulation:
  dt: 0.000000001
  adaptive: true
  grid:
    type: "EvenGrid"
    num_cells: 100
  num_save: 100
  duration: 0.002

postprocess:
  output_file:
    TwoZoneBohm: "/home/elida/Public/users/elsensoy/model_error_uq_plasma/hall_opt/results/output_twozonebohm.json"
    MultiLogBohm: "/home/elida/Public/users/elsensoy/model_error_uq_plasma/hall_opt/results/output_multilogbohm.json"
  save_time_resolved: false
  average_start_time: 0.004

inputs:
  V_a: 300
  mdot_a: 0.0001
  u_n: 141.24234
  l_t: 0.00187915
  a_1: 0.00680237
  a_2: 14.645
  dz: 0.4
  z0: -0.03
  p0: 0.0005686006

outputs:
  - name: I_B0
    description: Ion beam current
    units: A
    nominal: 3.6
    domain: (0, 10)
  - name: T
    description: Thrust
    units: N
    nominal: 0.08
    domain: (0, 0.2)
  - name: I_d
    description: Discharge current
    units: A
    nominal: 4.5
    domain: (0, 10)
  - name: eta_c
    description: Current efficiency
    domain: (0, 1)
