general:
  results_dir: "results"  # Base directory for results
  config_file: "config/settings.yaml"
  run_map: false     
  run_mcmc: false                     
  plotting: false    # Whether to generate plots
  subsampled: false
  ion_velocity_weight: 2.0  # Same for both MCMC and MAP
  iterations: 20  # Number of iterations

ground_truth:
  gen_data: true                
  results_dir: "${general.results_dir}/ground_truth"
  output_file: "${ground_truth.results_dir}/output_ground_truth.json"

#see error1.txt, error2.txt, error3.txt, error4.txt, error5.txt, error10.txt(magnetic field file), for included metrics
config_settings:
  thruster:
    geometry: #required by ht
      channel_length: 0.025 #required sub
      inner_radius: 0.0345 #required sub
      outer_radius: 0.05 #required sub
    magnetic_field:
      file: "config/bfield_spt100.csv"
  discharge_voltage: 300 #required by ht
  anode_mass_flow_rate: 5.0e-6 #required by ht
  domain: [0, 0.08] #required by ht
  anom_model:   # **THIS FIELD MUST EXIST**
    TwoZoneBohm:
      c1: 0.00625
      c2: 0.0625
    MultiLogBohm:
      zs: [0.0, 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07]
      cs: [0.02, 0.024, 0.028, 0.033, 0.04, 0.004, 0.004, 0.05]

postprocess:
  output_file:
    TwoZoneBohm: "${general.results_dir}/postprocess/output_twozonebohm.json"
    MultiLogBohm: "${general.results_dir}/postprocess/output_multilogbohm.json"

mcmc:
  results_dir: "${general.results_dir}/mcmc"
  base_dir: "${mcmc.results_dir}"
  save_interval: 10
  checkpoint_interval: 10
  save_metadata: true
  final_samples_file_log: "${mcmc.results_dir}/final_samples_log.csv"
  final_samples_file_linear: "${mcmc.results_dir}/final_samples_linear.csv"
  checkpoint_file: "${mcmc.results_dir}/checkpoint.json"
  metadata_file: "${mcmc.results_dir}/mcmc_metadata.json"
  initial_cov:
    - [0.1, 0.05]
    - [0.05, 0.1]  

map:
  results_dir: "${general.results_dir}/map"
  base_dir: "${map.results_dir}"
  map_initial_guess_file: "${map.results_dir}/initial_guess.json"
  iteration_log_file: "${map.base_dir}/map_sampling.json"
  final_map_params_file: "${map.results_dir}/final_map_params.json"
  method: "Nelder-Mead"
  maxfev: 5000
  fatol: 0.003
  xatol: 0.003

plots:
  results_dir: "${general.results_dir}/plots"
  plots_subdir: "${plots.results_dir}" 
  metrics_subdir: "${plots.results_dir}/iteration_metrics"
  enabled_plots:
    - "autocorrelation"
    - "trace"
    - "posterior"
    - "pair"

simulation:
  dt: 0.000001
  grid:
    type: "EvenGrid"
    num_cells: 100
  duration: 0.001 #see error6.txt, error7.txt, error8.txt for included metrics