results_dir: "results_test"
gen_data: true

#======CONFIG=====================
config_settings:
  thruster:
    name: "SPT-100"
  anom_model: #  anom model needs to be specified.(parameters)
    MultiLogBohm:
      zs: [0.0, 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07]
      cs: [0.02, 0.024, 0.028, 0.033, 0.04, 0.004, 0.004, 0.05]
##UNCOMMENT TWOZONEBOHM FOR MCMC/MAP 
    # TwoZoneBohm: 
    #   c1: 0.00625
    #   c2: 0.0625

##UNCOMMENT SECTIONS BELOW FOR TESTING MCMC/MAP/PLOTTING
# #======MAP_YAML=====================
# run_map: false
# map:
#   output_dir: "results_test/map"
#   initial_guess: [-0.2, 0.5]
#   method: "Nelder-Mead"
#   max_iter: 100
# #======MCMC_YAML=====================
# run_mcmc: true
# mcmc:
#   reference_data: "results_test/map/final_map_params.json"
#   output_dir: "results_test/mcmc"
#   initial_cov: [[1.0, 0.0], [0.0, 1.0]]
#   burn_in: 20
#   max_iter: 100

# #======PLOTTING_YAML=====================
# plotting: true
